apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
spec:
  selector:
    app.kubernetes.io/name: database
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
