services:

  proxy:
    image: nginx:1.29-alpine

  backend:
    build:
      dockerfile: ./docker-compose/backend/Dockerfile
    environment:
      FLASK_DB_TYPE: postgres
      FLASK_DB_USER: postgres
      FLASK_DB_NAME: postgres
      FLASK_DB_PASSWORD: postgres
      FLASK_DB_HOST: database
      FLASK_DB_PORT: 5432
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ CMD, pg_isready ]
      interval: 3s
      timeout: 1s
      retries: 10
