services:

  backend:
    build:
      dockerfile: ./docker-compose/backend/Dockerfile
    environment:
      FLASK_DB_TYPE: postgres
      FLASK_DB_USER: postgres
      FLASK_DB_NAME: postgres
      FLASK_DB_PASSWORD: postgres
      FLASK_DB_HOST: database
      FLASK_DB_PORT: 5432

  database:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_PASSWORD: postgres
