# TODO HealthCheck
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app.kubernetes.io/part-of: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version | quote }}
    spec:
      containers:
        - name: backend
          image: wandersonwhcr/guess_game_backend:v1.0
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: FLASK_DB_TYPE
              value: postgres
            - name: FLASK_DB_HOST
              value: database-postgresql.database.svc
            - name: FLASK_DB_PORT
              value: "5432"
            - name: FLASK_DB_USER
              value: postgres
            - name: FLASK_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: guess-game-database-credentials
                  key: FLASK_DB_PASSWORD
            - name: FLASK_DB_NAME
              value: postgres
          lifecycle:
            preStop:
              exec:
                command: [ /bin/sh, -c, kill -INT 1 ]
