backend:
  database:
    type: postgres
    host: database-postgresql.database.svc
    port: 5432
    name: postgres
    user: postgres
    pass:
      secretKeyRef:
        name: guess-game-database-credentials
        key: FLASK_DB_PASSWORD
  ingress:
    host: backend.guess-game.minikube

frontend:
  ingress:
    host: frontend.guess-game.minikube
